# NuGet test pipeline

trigger: none

parameters:
- name: DartLabEnvironment
  displayName: DartLab Environment
  type: string
  default: Production
  values:
  - Production
  - Staging

resources:
  pipelines:
  - pipeline: NuGet
    source: NuGet.Client-PrivateDev
  - pipeline: DartLab
    source: DartLab
    branch: main
  repositories:
  - repository: DartLabTemplates
    type: git
    name: DartLab.Templates
    ref: refs/heads/main

stages:
- name: GetVSBootstrapperUri
  displayName: Get VS Bootstrapper URI
  pool:
    vmImage: windows-latest
  jobs:
  - job: GetFromBuildArtifact
    steps:
    - download: NuGet
      artifact: MicroBuildOutputs
      displayName: Download BootstrapperInfo.json
    - task: PowerShell@1
      displayName: "Set Bootstrapper URL variable"
      name: "vsbootstrapper"
      inputs:
        scriptType: "inlineScript"
        inlineScript: |
          try {
            $json = Get-Content "${env:Build_StagingDirectory}\NuGet\MicroBuildOutputs\BootstrapperInfo.json" | ConvertFrom-Json
            $bootstrapperUrl = $json[0].bootstrapperUrl;
            Write-Host "Bootstrapper URL: $bootstrapperUrl"
            Write-Host "##vso[task.setvariable variable=bootstrapperUrl;isOutput=true]$bootstrapperUrl"
          } catch {
            Write-Host "##vso[task.LogIssue type=error;]Unable to set bootstrapperUrl: $_"
            exit 1
          }

- template: stages\visual-studio\single-runsettings.yml@DartLabTemplates
  parameters:
    name: RunOnDartlab
    displayName: Run NuGet.OptProf.dll
    dependsOn: GetVSBootstrapperUri
    variables:
    - name: bootstrapperUrl
      value: $[stageDependencies.GetVSBootstrapperUri.GetFromBuildArtifact.outputs['vsbootstrapper.bootstrapperUrl']]
    runSettingsURI: $(Pipeline.Workspace)\NuGet\RunSettings\NuGet.OptProfV2.runsettings
    visualStudioBootstrapperURI: $(bootstrapperUrl)
    testLabPoolName: VS-Platform
    dartLabEnvironment: ${{parameters.DartLabEnvironment}}
    visualStudioSigning: Test
    preTestMachineConfigurationStepList:
    - download: NuGet
      artifact: RunSettings
      displayName: Download NuGet RunSettings
    preDeployAndRunTestsStepList:
    - download: NuGet
      artifact: RunSettings
      displayName: Download NuGet RunSettings
