# NuGet test pipeline

trigger: none

parameters:
- name: DartLabEnvironment
  displayName: DartLab Environment
  type: string
  default: Production
  values:
  - Production
  - Staging

resources:
  pipelines:
  - pipeline: NuGet
    source: NuGet.Client-Official
  - pipeline: DartLab
    source: DartLab
    branch: main
  repositories:
  - repository: DartLabTemplates
    type: git
    name: DartLab.Templates
    ref: refs/heads/main

stages:
- template: stages\visual-studio\single-runsettings.yml@DartLabTemplates
  parameters:
    displayName: NuGet Test Environment
    runSettingsURI: $(Pipeline.Workspace)\NuGet\RunSettings\NuGet.OptProfV2.runsettings
    visualStudioBootstrapperURI: $(Pipeline.Workspace)\NuGet\VS15\4786489\646a52be-73ec-4f9e-8546-20f961a7cba0\vs_enterprise.exe
    testLabPoolName: VS-Platform
    dartLabEnvironment: ${{parameters.DartLabEnvironment}}
    visualStudioSigning: Test
    preSetSetupParametersStepList:
    - download: NuGet
      artifact: RunSettings
      displayName: Download NuGet RunSettings
    - download: NuGet
      artifact: VS15
      displayName: Download NuGet RunSettings
    preDeployAndRunTestsStepList:
    - download: NuGet
      artifact: RunSettings
      displayName: Download NuGet RunSettings
    - download: NuGet
      artifact: VS15
      displayName: Download NuGet RunSettings
