# NuGet test pipeline

trigger: none

parameters:
- name: DartLabEnvironment
  displayName: DartLab Environment
  type: string
  default: Production
  values:
  - Production
  - Staging

resources:
  pipelines:
  - pipeline: NuGet
    source: NuGet.Client-Official
  - pipeline: DartLab
    source: DartLab
    branch: dev/bradwhit/ConvertRPSPipelines
  repositories:
  - repository: DartLabTemplates
    type: git
    name: DartLab.Templates
    ref: refs/heads/dev/bradwhit/ConvertRPSPipelines

stages:
- template: stages\visual-studio\default.yml@DartLabTemplates
  parameters:
    displayName: NuGet Test Environment
    runSettingsURI: $(Pipeline.Workspace)\NuGet\RunSettings\NuGet.OptProfV2.runsettings
    visualStudioBootstrapperURI: https://vsdrop.corp.microsoft.com/file/v1/Products/DevDiv/NuGet-NuGet.Client-Trusted/dev-zivkan-dartlab/6.0.0.33;bootstrapper/4740532/f67dda70-85cc-4474-9da7-3cbb040e3581/vs_enterprise.exe
    testLabPoolName: VS-Platform
    dartLabEnvironment: ${{parameters.DartLabEnvironment}}
    visualStudioSigning: Test
