trigger: none
resources:
  pipelines:
  - pipeline: NuGet.Client-Official
    source: NuGet.Client-Official
  - pipeline: DartLab
    project: Engineering
    source: DartLab
    branch: main
  repositories:
  - repository: DartLabTemplates
    type: git
    name: Engineering/DartLab

parameters:
- name: NumberOfTestMachines
  displayName: Number of Test Machines
  type: number
  default: 1
- name: DartLabEnvironment
  displayName: DartLab Environment
  type: string
  default: Production
  values:
  - Production
  - Staging

variables: # pipeline-level
- group: DartLab Secrets
- name: RunSettingsURI
  value: $(Pipeline.Workspace)\NuGet.Client-Official\BuildArtifacts\RunSettings\NuGet.OptProfV2.runsettings
- name: VisualStudioBootstrapperURI
  value: https://vsdrop.corp.microsoft.com/file/v1/$(DartLab_ProductsDropName);bootstrappers/Enterprise/vs_enterprise.exe
- name: VSSigning
  value: Test
- template: Templates\Variables\DevTestLabs\Labs\DDRITS-PUBLIC.yml@DartLabTemplates

stages:
- stage: NuGetOptProfTests
  displayName: 'Run NuGet.OptProf tests'

  jobs:
  - template: Templates\Steps\DevTestLabs\Configurations\DefaultTemplates\VisualStudio.Default.yml@DartLabTemplates
    parameters:
      dartLabEnvironment: ${{ parameters.DartLabEnvironment }}
      dtlLab: '${{variables.DartLab_DTLLabs}}'
      numberOfTestMachines: ${{parameters.NumberOfTestMachines}}
      runSettingsUri: '${{ variables.RunSettingsURI }}'
      visualStudioBootstrapperURI: '${{ variables.VisualStudioBootstrapperURI}}'
      visualStudioSigning: '${{variables.VSSigning}}'
      preInitializeTestMachineConfigurationStepList:
        - checkout: none
      preInitializeTestExecutionStepList:
        - checkout: none
